sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t lionotm/docker-poc -f Dockerfile.dev .

script:
  - docker run -e CI=true lionotm/docker-poc npm run test -- --coverage
